name: Build MeshDesk for IPQ50xx

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build meshdesk + luci-app-meshdesk
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Clone openwrt-meshdesk
        run: |
          mkdir -p package
          git clone https://github.com/RADIUSdesk/openwrt-meshdesk.git tmp
          cp -r tmp/MESHdesk package/meshdesk
          cp -r tmp/luci-app-meshdesk package/luci-app-meshdesk

      - name: Build with OpenWrt SDK
        uses: openwrt/gh-action-sdk@v1
        with:
          target: ipq50xx
          subtarget: generic
          version: SNAPSHOT
          packages: |
            meshdesk
            luci-app-meshdesk
