name: Build MeshDesk for OpenWrt IPQ50xx

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build MeshDesk
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Clone openwrt-meshdesk
        run: |
         mkdir -p package
         git clone https://github.com/RADIUSdesk/openwrt-meshdesk.git tmp
         cp -r tmp/source/* package/
      
      - name: Build using OpenWrt SDK
        uses: openwrt/gh-action-sdk@v1
        with:
          target: ipq50xx
          subtarget: generic
          version: SNAPSHOT
          packages: |
            meshdesk
            luci-app-meshdesk
